/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PrivacyPassInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeIssuer"
      | "authorizedIssuers"
      | "owner"
      | "registerCredential"
      | "revokeCredential"
      | "verifyCredential"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CredentialRegistered"
      | "CredentialRevoked"
      | "IssuerAuthorizationUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeIssuer",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedIssuers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerCredential",
    values: [BytesLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCredential",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCredential",
    data: BytesLike
  ): Result;
}

export namespace CredentialRegisteredEvent {
  export type InputTuple = [
    credentialHash: BytesLike,
    issuer: AddressLike,
    subject: AddressLike,
    expiresAt: BigNumberish,
    zkCommitment: BytesLike
  ];
  export type OutputTuple = [
    credentialHash: string,
    issuer: string,
    subject: string,
    expiresAt: bigint,
    zkCommitment: string
  ];
  export interface OutputObject {
    credentialHash: string;
    issuer: string;
    subject: string;
    expiresAt: bigint;
    zkCommitment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [credentialHash: BytesLike, issuer: AddressLike];
  export type OutputTuple = [credentialHash: string, issuer: string];
  export interface OutputObject {
    credentialHash: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerAuthorizationUpdatedEvent {
  export type InputTuple = [issuer: AddressLike, allowed: boolean];
  export type OutputTuple = [issuer: string, allowed: boolean];
  export interface OutputObject {
    issuer: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivacyPass extends BaseContract {
  connect(runner?: ContractRunner | null): PrivacyPass;
  waitForDeployment(): Promise<this>;

  interface: PrivacyPassInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeIssuer: TypedContractMethod<
    [issuer: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  authorizedIssuers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerCredential: TypedContractMethod<
    [
      credentialHash: BytesLike,
      subject: AddressLike,
      expiresAt: BigNumberish,
      zkCommitment: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  revokeCredential: TypedContractMethod<
    [credentialHash: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyCredential: TypedContractMethod<
    [credentialHash: BytesLike],
    [
      [boolean, boolean, bigint, string, string] & {
        valid: boolean;
        revoked: boolean;
        expiresAt: bigint;
        issuer: string;
        subject: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeIssuer"
  ): TypedContractMethod<
    [issuer: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedIssuers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerCredential"
  ): TypedContractMethod<
    [
      credentialHash: BytesLike,
      subject: AddressLike,
      expiresAt: BigNumberish,
      zkCommitment: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<[credentialHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyCredential"
  ): TypedContractMethod<
    [credentialHash: BytesLike],
    [
      [boolean, boolean, bigint, string, string] & {
        valid: boolean;
        revoked: boolean;
        expiresAt: bigint;
        issuer: string;
        subject: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CredentialRegistered"
  ): TypedContractEvent<
    CredentialRegisteredEvent.InputTuple,
    CredentialRegisteredEvent.OutputTuple,
    CredentialRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerAuthorizationUpdated"
  ): TypedContractEvent<
    IssuerAuthorizationUpdatedEvent.InputTuple,
    IssuerAuthorizationUpdatedEvent.OutputTuple,
    IssuerAuthorizationUpdatedEvent.OutputObject
  >;

  filters: {
    "CredentialRegistered(bytes32,address,address,uint256,bytes32)": TypedContractEvent<
      CredentialRegisteredEvent.InputTuple,
      CredentialRegisteredEvent.OutputTuple,
      CredentialRegisteredEvent.OutputObject
    >;
    CredentialRegistered: TypedContractEvent<
      CredentialRegisteredEvent.InputTuple,
      CredentialRegisteredEvent.OutputTuple,
      CredentialRegisteredEvent.OutputObject
    >;

    "CredentialRevoked(bytes32,address)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "IssuerAuthorizationUpdated(address,bool)": TypedContractEvent<
      IssuerAuthorizationUpdatedEvent.InputTuple,
      IssuerAuthorizationUpdatedEvent.OutputTuple,
      IssuerAuthorizationUpdatedEvent.OutputObject
    >;
    IssuerAuthorizationUpdated: TypedContractEvent<
      IssuerAuthorizationUpdatedEvent.InputTuple,
      IssuerAuthorizationUpdatedEvent.OutputTuple,
      IssuerAuthorizationUpdatedEvent.OutputObject
    >;
  };
}
